### ISSUE TITLE
Typescript issue#5787 referenced in README.md is closed

### ISSUE THREAD

**Issue by gitgrimbo** [dojo/typings#108]
Section **AMD Plugin Globbing**.

*... There is an open ticket for this type of support (see Microsoft/TypeScript#5787) ...*

**Comment by dylans** [comment]
Ah yes, wildcard globbing was added in TS 2.0 (see section on https://www.sitepen.com/blog/2016/09/01/typescript-2-0-awesomeness/ for example)... do you want to create a PR or should I, @gitgrimbo ?

**Comment by gitgrimbo** [comment]
Hi @dylans.  If you could handle it please, as I'm not well-versed enough in the original issue or the current approach for `dojo/text`.  E.g. should the _AMD Plugin Globbing_ section be removed entirely, or replaced with a current example of how to use `dojo/text`?
Thanks.

**Comment by dylans** [comment]
Ok, will do, it should be replaced with a current example. e.g. something like:

```
declare module "dojo/text!*" {
    let text: any;
    export default text;
}
 
import foo from "dojo/text!a/b/foo.txt";
// lookup:
//    dojo/text!a/b/foo.txt
//    dojo/text!*
```
