### ISSUE TITLE
Add a build step for consolidating typings into a single file?

### ISSUE THREAD

**Issue by ca0v** [dojo/typings#13]
It would be very nice to have a single index.d.ts file with everything in there (one each for dojo, dijit).

**Comment by kitsonk** [comment]
@ca0v we will look at this, but I am not sure what the benefit would be.

**Comment by ca0v** [comment]
If you build and commit the index.d.ts then I could use [typings](https://github.com/typings/typings/) to pull that single file.  What is missing is how to use typings with this repository; typings might also combine to single index.d.ts file?

**Comment by kitsonk** [comment]
Sorry for the delay... We are going to do our best to find a way to make this work with typings (See #11) and if that requires a single final file, then that is what we have to do.  It just makes it hard to maintain and then adding/maintain stuff.  So I am going to close this for now, in lieu of just making #11 work, however it need to work.
