### ISSUE TITLE
Can't use Deferred as a type

### ISSUE THREAD

**Issue by joejohndoe** [dojo/typings#16]
#### Repro case

``` ts
import Deferred = require("dojo/Deferred");

interface SomeInterface {
  dfd: Deferred<SomeType>;
  // ...
}

export function process(): IPromise<SomeType> {
  let dfd = new Deferred<SomeType>();
  // ...
  return dfd;
}
```
#### Problem

The repro case results in a `TS2304: Cannot find name 'Deferred'` compiler message for the usage of `Deferred` as type in the interface, but not for the usage as constructor in the function.
#### Solution

Changing the declaration Deferred in  `module.d.ts` to 

``` ts
declare module 'dojo/_base/Deferred' {
    type Deferred = dojo._base.Deferred;
    const Deferred: dojo._base.DeferredConstructor;
    export = Deferred;
}
```

fixes the problem.

**Comment by kitsonk** [comment]
Correct, the typing is wrong.

**Comment by bitranch** [comment]
The typings are namespaced, so your example could be fixed by simply adding the "dojo." namespace:

``` typescript
interface SomeInterface {
  dfd: dojo.Deferred<SomeType>;
}
```

**Comment by kitsonk** [comment]
@bitranch but what I didn't realise is you can merge the types too... which makes it handy!  I learned something new.

**Comment by bitranch** [comment]
True. But since he's importing from 'dojo/Deferred' setting the type in 'dojo/_base/Deferred' might not fix this particular issue.

**Comment by kitsonk** [comment]
True... the change I pushed was related to what he mentioned he imported.  Didn't realise he was importing from one but referring to another.

**Comment by kitsonk** [comment]
Ok, I have rolled this out to I think everything we currently have in the repo that it applies to.
