### ISSUE TITLE
dojo.date.Date namespace hides global Date in dojo.date typings

### ISSUE THREAD

**Issue by bitranch** [dojo/typings#18]
The dojo/date functions taking a Date object fail because the dojo.date.Date namespace is used instead of the global Date. Thus, both of these produce an error in TS since it's looking for a dojo.date.Date:

``` typescript
const dt = new Date();
toISOString(dt);
isLeapYear(dt);
```

**Comment by andrewcbancroft** [comment]
I just ran into this and I'm so grateful that you created a fix.
