### ISSUE TITLE
DocumentEvent - Cannot find name DocumentEvent

### ISSUE THREAD

**Issue by davewilton** [dojo/typings#184]
The documentEvent interface appears to have been removed from Typescript in version 4.4. 

https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts

Maybe I'm confused but should these not have been the Event interface anyway? 

https://github.com/microsoft/TypeScript/blob/release-4.4/lib/lib.dom.d.ts#L5059

**Comment by dylans** [comment]
Thanks for the PR.
