### ISSUE TITLE
Move to UMD Definitions

### ISSUE THREAD

**Issue by kitsonk** [dojo/typings#25]
TypeScript supports the concept of having a type definition as a "module" which allows it then to be further consumed and namespaced downstream.  Currently the way our type definitions are defined are as "global" which means that tooling (like typings/typings) cannot easily namespace modules, which would be great.  It also means that it doesn't auto concatenate the files.

I am going to start this work on a new branch, to see how difficult it would be.

**Comment by kitsonk** [comment]
See also dojo/meta#46 and dojo/meta#62

**Comment by agubler** [comment]
@kitsonk does the move to UMD typings across our modules resolve this issue?

**Comment by kitsonk** [comment]
It does for those packages, but wouldn't allow you to do it with Dojo 1 unless we converted to UMD.

**Comment by agubler** [comment]
We could and would still use `typings/typings` for dojo 1

**Comment by kitsonk** [comment]
We could, but it makes it difficult for people to namespace `dojo`, `dijit`, etc. and it doesn't reflecting, typing wise, what the actual code is doing, which would access the typings in a more modular way, exactly like the way Dojo 1 works.

This ticket isn't a priority.

**Comment by schungx** [comment]
Think of the poor guys out there who are just trying to whip up a small web app here and there...  they don't want to bother with a build tool.

With AMD modules, said guy can just concat up the necessary module files, probably with a simple shell script or a batch file.

With UMD modules, he needs to do a bunch of transformations.

So, use a better loader (one that handles all module formats) instead.

**Comment by kitsonk** [comment]
@schungx I think you are mis-understanding.  We aren't talking about `UMD` for Dojo 1, we are talking about the _UMD_ definition format for TypeScript, where there is a file for each `.js` file as part of Dojo 1.  When TypeScript acquires these types, they are scoped only to match the module they refer to and don't require a global `namespace` and would allow us to better model the actual behaviours of the Dojo 1 code.

**Comment by kitsonk** [comment]
(Also, I should note that it was confusing that the TypeScript team refer to these non global definition files as _UMD_ definition files, but we didn't have control over their choice of name)
