### ISSUE TITLE
Additional dijit/layout typing

### ISSUE THREAD

**Issue by bitranch** [dojo/typings#3]
I'm working on a PR for the following dijit/layout related typing:
- dijit/_Contained
- dijit/_WidgetsInTemplateMixin
- dijit/layout/_LayoutWidget
- dijit/layout/StackContainer
- dijit/layout/StackController

Also adding module definitions to make some dijit base classes importable:
- dijit/_WidgetBase
- dijit/_TemplatedMixin

(Let me know if these collide with anything @kitsonk is working on.)

**Comment by dylans** [comment]
@bitranch, go for it, the help is very much appreciated!
