### ISSUE TITLE
Publish 1.11.0-pre to npm

### ISSUE THREAD

**Issue by odoe** [dojo/typings#7]
I don't know what your exact timeframe is for 1.11 final, but would it be possible for you to publish the 1.11.0-pre of the typings to npm? I'm using them with 1.10.4 now and the current npm release is missing some key dijit definitions that are in pre.

Thanks!

**Comment by kitsonk** [comment]
I was going to do a 1.11.0 tomorrow.

**Comment by kitsonk** [comment]
Also for note, `"dojo-typings": "dojo/typings#master"` would at least install the package.  There is no real build step, so what I push to NPM is what would be retrieved by that.
